//Login
export const AUTHENTICATE_LOGIN_REQUEST = 'AUTHENTICATE_LOGIN_REQUEST';
export const AUTHENTICATE_LOGIN_SUCESS = 'AUTHENTICATE_LOGIN_SUCESS';
export const AUTHENTICATE_LOGIN_FAILURE = 'AUTHENTICATE_LOGIN_FAILURE';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_REMEMBER_OPTION = 'SET_REMEMBER_OPTION';
export const GET_REMEMBER_OPTION = 'GET_REMEMBER_OPTION';

//Dashboard
export const GET_GRID_DATA_REQUEST = "GET_GRID_DATA_REQUEST";
export const GET_GRID_DATA_SUCCESS = "GET_GRID_DATA_SUCCESS";
export const GET_GRID_DATA_FAILURE = "GET_GRID_DATA_FAILURE";

export const GET_INITIAL_REGION = "GET_INITIAL_REGION";
export const SET_INITIAL_REGION = "SET_INITIAL_REGION";

export const GET_GRID_DROPDOWN_REQUEST = "GET_GRID_DROPDOWN_REQUEST";
export const GET_GRID_DROPDOWN_SUCCESS = "GET_GRID_DROPDOWN_SUCCESS";
export const GET_GRID_DROPDOWN_FAILURE = "GET_GRID_DROPDOWN_FAILURE";

export const SET_CURRENT_LOCATION_HANDLED = "SET_CURRENT_LOCATION_HANDLED";
export const GET_CURRENT_LOCATION_HANDLED = "GET_CURRENT_LOCATION_HANDLED";

export const GET_CURRENT_GRID_DETAILS = "GET_CURRENT_GRID_DETAILS";
export const SET_CURRENT_GRID_DETAILS = "SET_CURRENT_GRID_DETAILS";

export const GET_CURRENT_LOC = "GET_CURRENT_LOC";
export const SET_CURRENT_LOC = "SET_CURRENT_LOC";

export const SET_WATCH_ID = "SET_WATCH_ID";

export const GET_SEARCH_GRID = "GET_SEARCH_GRID";
export const SET_SEARCH_GRID = "SET_SEARCH_GRID";
